version: "3"


services:
  redis:
    image: redis:4.0.1-alpine
    volumes:
      - redis-data:/data
    ports:
      - "6379"

  dynamodb-test:
    build:
      context: .
      dockerfile: docker/dynamodb/Dockerfile
    command: -jar DynamoDBLocal.jar --inMemory
    ports:
      - "8002:8000"

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./:/var/task
    environment: &environment
      - ALFRED_EMAIL_VERIFY_TOKEN=${ALFRED_EMAIL_VERIFY_TOKEN}
      - ALFRED_PASSWORD_SALT=esquilo
      - ALFRED_REDIS_HOST=redis
      - AWS_ACCESS_KEY_ID=aws_access_key
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_SECRET_ACCESS_KEY=aws_access_secret
      - BUCKET_S3=fake_bucket
      - DEFAULT_STORAGE=dummy
      - DYNAMODB_HOST=http://dynamodb-test:8000
      - DYNAMODB_PREFIX=alfred
      - FERNET_CRYPT_KEY=ank2C0xNzXJn6rfdJ3nS5zMkClU0I34tuQMXpVmX6yM=
      - JWT_ALGORITHM=HS256
      - JWT_EXP_DELTA_SECONDS=604800
      - JWT_SECRET=fake_secret
    ports:
      - "8108:8108"
    depends_on:
      - "redis"
      - "dynamodb-test"
volumes:
  redis-data:
